on:
  workflow_call:
    inputs:
      image-builder-name:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_RG:
        required: true
      AZURE_SUBSCRIPTION:
        required: true
concurrency: deployment_environment
name: Delete Image Builder
jobs:
  delete-image-builder:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Cancel image builder if in progress
      uses: Azure/cli@v1
      with:
        inlineScript: az image builder cancel --resource-group ${{ secrets.AZURE_RG }} --name ${{ inputs.image-builder-name }} || true
    
    - name: Wait image builder stops
      uses: Azure/cli@v1
      with:
        inlineScript: (az image builder show --resource-group ${{ secrets.AZURE_RG }} --name ${{ inputs.image-builder-name }} && az image builder wait --resource-group ${{ secrets.AZURE_RG }} --name ${{ inputs.image-builder-name }} --custom "lastRunStatus.runState!='Canceling'") || true
         
    -  name: Delete previous image builder
       uses: Azure/cli@v1
       with:
         inlineScript: az image builder delete --resource-group ${{ secrets.AZURE_RG }} --name ${{ inputs.image-builder-name }}
    