on: [push]
name: Image Builder Bicep
jobs:
  deploy-bicep:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    -  name: Azure CLI Action
       uses: Azure/cli@v1
       with:
          # Specify the script here
         inlineScript: az image builder delete --resource-group ${{ secrets.AZURE_RG }} --name imageBuilder
    
      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: 'imageBuilderName=imageBuilder destinationGalleryName=hpcgallery destinationGalleryDescription="HPC Gallery" destinationImageName=ubuntuhpc destinationImageDescription="Ubuntu HPC"'
        failOnStdErr: false
