on:
  push:
    branches:
    - main
concurrency: deployment_environment
name: Image Builder Bicep
jobs:
  delete-image-builder:
    uses: ./.github/workflows/delete-image-builder.yml
    with:
      image-builder-name: 'imageBuilder'
    secrets: inherit

  deploy-bicep:
    needs: delete-image-builder
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main
    
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: Deploy Bicep resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./image-builder.bicep
        parameters: 'imageBuilderName=imageBuilder destinationGalleryName=hpcgallery destinationImageName=ubuntuhpc'
        failOnStdErr: false
        
  run-builder:
    needs: [deploy-bicep, delete-image-builder]
    uses: ./.github/workflows/run-image-builder.yml
    with:
      image-builder-name: 'imageBuilder'
    secrets: inherit
